In [48]:
import pandas as pd
import numpy as np

In [2]:
xl = pd.ExcelFile('/Users/sergey/Documents/TUM/IDP/prepared_instruments.xlsx')

In [50]:
df = xl.parse("FY0")
dfTime = xl.parse("TS")

,Date,TGTG.DE,TGTG.DE.1,UUUG.DE,UUUG.DE.1,VSCk.DE,VSCk.DE.1,HRPKk.F,HRPKk.F.1,LUMG.F,...,YB1.F,YB1.F.1,RTVGn.F,RTVGn.F.1,ZALG.DE,ZALG.DE.1,ZEFG.DE,ZEFG.DE.1,ZO1G.DE,ZO1G.DE.1
0,Timestamp,Trade Open,Trade Close,Trade Open,Trade Close,Trade Open,Trade Close,Trade Open,Trade Close,Trade Open,...,Trade Open,Trade Close,Trade Open,Trade Close,Trade Open,Trade Close,Trade Open,Trade Close,Trade Open,Trade Close
2,2016-11-30 00:00:00,0.63,0.68,0.641,0.641,2.496,2.451,2.254,2.281,0.016,...,0.02,0.02,1.22,1.22,35.855,35.165,NaN,NaN,123.2,121
4,2016-11-28 00:00:00,0.686,0.7,0.65,0.65,2.52,2.5,2.36,2.324,0.016,...,0.02,0.02,1.221,1.221,36.05,35.22,NaN,NaN,122.5,123
6,2016-11-24 00:00:00,NaN,NaN,0.661,0.656,2.412,2.401,2.288,2.373,0.016,...,0.02,0.02,1.22,1.22,35.62,35.345,NaN,NaN,120.5,121
8,2016-11-22 00:00:00,0.796,0.728,0.65,0.647,NaN,NaN,2.26,2.335,0.016,...,0.02,0.02,1.275,1.275,35.97,35.895,1.46,1.46,119.1,119.85
10,2016-11-18 00:00:00,0.81,0.772,0.68,0.645,2.532,2.488,2.28,2.296,0.017,...,0.021,0.021,1.255,1.338,35.57,35.665,NaN,NaN,122.05,123.05
12,2016-11-16 00:00:00,0.78,0.781,0.679,0.679,2.44,2.395,2.238,2.246,0.016,...,0.021,0.021,1.37,1.37,34.8,35.005,1.507,1.507,124.7,125.4
14,2016-11-14 00:00:00,0.796,0.796,0.663,0.663,2.544,2.522,2.329,2.243,0.016,...,0.021,0.021,1.37,1.37,35.845,34.785,1.547,1.547,126.8,125.25
16,2016-11-10 00:00:00,0.801,0.814,0.64,0.64,2.429,2.489,2.21,2.19,0.016,...,0.021,0.021,1.3,1.415,38.55,34.87,1.53,1.5,128.45,128.4
18,2016-11-08 00:00:00,0.813,0.813,0.638,0.64,2.37,2.369,2.22,2.259,0.016,...,0.021,0.021,1.265,1.265,36.825,36.9,NaN,NaN,128.6,128.35
20,2016-11-04 00:00:00,0.812,0.812,0.65,0.645,2.405,2.405,2.219,2.213,0.016,...,0.021,0.021,1.265,1.265,38.45,38.415,NaN,NaN,128.5,127.6
22,2016-11-02 00:00:00,0.832,0.832,0.65,0.65,2.55,2.405,2.267,2.299,0.016,...,0.021,0.021,1.28,1.265,39.02,38.48,1.617,1.6,129.45,128.5
24,2016-10-31 00:00:00,0.85,0.85,0.649,0.67,2.569,2.6,2.31,2.291,0.017,...,0.021,0.021,1.28,1.28,39.695,39.99,1.617,1.617,130.45,129.55
26,2016-10-27 00:00:00,NaN,NaN,0.634,0.645,2.511,2.431,2.251,2.291,0.017,...,0.02,0.02,1.35,1.35,39.895,40.35,1.67,1.6,128.5,129.5
28,2016-10-25 00:00:00,NaN,NaN,0.64,0.648,2.48,2.51,2.31,2.31,0.016,...,0.021,0.021,1.35,1.35,40.16,40.225,1.88,1.73,128,128.05
30,2016-10-21 00:00:00,0.832,0.832,0.64,0.64,2.515,2.485,2.379,2.379,0.016,...,0.04,0.03,1.4,1.4,40.4,39.61,1.88,1.835,130,129.7
32,2016-10-19 00:00:00,0.84,0.84,0.641,0.641,2.484,2.41,2.42,2.426,0.016,...,0.02,0.048,1.4,1.4,38.25,39.905,1.706,1.87,128.45,129.5
34,2016-10-17 00:00:00,0.891,0.84,0.65,0.65,2.531,2.446,2.416,2.416,0.016,...,0.02,0.028,1.4,1.4,37.76,37.21,NaN,NaN,128,127.65
36,2016-10-13 00:00:00,0.969,0.936,NaN,NaN,2.532,2.531,2.452,2.442,0.016,...,0.045,0.04,1.4,1.4,37.35,37.08,NaN,NaN,127.5,127.1
38,2016-10-11 00:00:00,0.966,0.965,NaN,NaN,2.555,2.531,2.461,2.498,0.016,...,0.04,0.046,1.4,1.4,37.03,37.61,NaN,NaN,130.5,130.25
40,2016-10-07 00:00:00,0.962,0.965,0.641,0.641,2.746,2.672,2.45,2.45,0.016,...,0.05,0.06,1.4,1.4,37.5,36.97,NaN,NaN,128,129.45
42,2016-10-05 00:00:00,1,0.992,0.65,0.65,2.279,2.827,2.457,2.45,0.015,...,0.07,0.07,1.4,1.4,37.7,37.96,NaN,NaN,129.35,128.95
44,2016-09-30 00:00:00,NaN,NaN,0.651,0.651,2.139,2.199,2.447,2.491,0.015,...,0.06,0.055,1.4,1.401,36,37.15,NaN,NaN,126.05,129
46,2016-09-28 00:00:00,0.991,0.991,0.669,0.669,2.272,2.201,2.5,2.491,0.015,...,0.08,0.08,1.4,1.4,36.735,36.345,1.903,1.64,127,127.9
48,2016-09-26 00:00:00,1.049,1.049,0.646,0.646,2.19,2.19,2.539,2.498,0.015,...,0.07,0.09,1.4,1.4,37.105,36.74,1.7,1.7,129.9,127.05
50,2016-09-22 00:00:00,1.031,1.031,0.649,0.649,2.199,2.239,2.49,2.461,0.015,...,0.06,0.07,1.4,1.4,36.71,36.99,NaN,NaN,127.65,131.7
52,2016-09-20 00:00:00,1.004,1.004,0.643,0.643,2.199,2.128,2.5,2.5,0.015,...,0.027,0.027,1.4,1.401,36.39,36.385,1.65,1.65,129,127.8
54,2016-09-16 00:00:00,0.937,0.935,0.625,0.625,2.18,2.191,2.5,2.499,0.015,...,0.027,0.027,1.4,1.4,35.02,35.19,1.7,1.7,128.9,129.3
56,2016-09-14 00:00:00,0.968,0.96,0.63,0.63,2.183,2.256,2.488,2.68,0.015,...,0.027,0.027,1.4,1.4,35.35,35.245,1.742,1.742,125.5,128.45
58,2016-09-12 00:00:00,0.942,0.94,NaN,NaN,2.1,2.102,2.639,2.579,0.015,...,0.027,0.027,1.4,1.401,35,35.155,NaN,NaN,125.5,127
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2720,2006-03-23 00:00:00,20,19.8,0.89,0.91,23.5979,24.1499,45.96,45.9,0.44,...,NaN,NaN,2.06759,2.29733,NaN,NaN,NaN,NaN,NaN,NaN
2722,2006-03-21 00:00:00,20.11,20.11,0.91,0.9,22.5399,23.0919,47,47.16,0.44,...,NaN,NaN,1.91444,1.94315,NaN,NaN,NaN,NaN,NaN,NaN
2724,2006-03-17 00:00:00,19.3,19.6,0.91,0.9,21.6199,21.8499,46.3,44.6,0.44,...,NaN,NaN,2.2016,2.05802,NaN,NaN,NaN,NaN,NaN,NaN
2726,2006-03-15 00:00:00,19.7,19.49,0.96,0.93,20.7919,21.6199,46.6,46.9,0.46,...,NaN,NaN,2.23032,2.22075,NaN,NaN,NaN,NaN,NaN,NaN
2728,2006-03-13 00:00:00,19.26,19.5,0.94,0.96,20.6539,20.6999,47.1,47.68,0.48,...,NaN,NaN,2.21118,2.29733,NaN,NaN,NaN,NaN,NaN,NaN
2730,2006-03-09 00:00:00,19.55,19.52,0.92,0.92,20.4699,20.4699,43.16,44.78,0.48,...,NaN,NaN,2.2016,2.2016,NaN,NaN,NaN,NaN,NaN,NaN
2732,2006-03-07 00:00:00,20.74,20.8,0.91,0.91,20.4239,20.4239,47.88,46.38,0.49,...,NaN,NaN,2.34519,2.24946,NaN,NaN,NaN,NaN,NaN,NaN
2734,2006-03-03 00:00:00,21,21,0.91,0.89,20.4699,20.4699,48.4,47.7,0.48,...,NaN,NaN,2.35476,2.35476,NaN,NaN,NaN,NaN,NaN,NaN
2736,2006-03-01 00:00:00,20.9,20.94,0.93,0.94,20.4699,20.4699,46.7,45.6,0.51,...,NaN,NaN,2.34519,2.36433,NaN,NaN,NaN,NaN,NaN,NaN
2738,2006-02-27 00:00:00,21.03,20.9,0.87,0.86,20.5619,20.4699,47.8,50.6,0.52,...,NaN,NaN,2.46005,2.39305,NaN,NaN,NaN,NaN,NaN,NaN
2740,2006-02-23 00:00:00,20.75,20.87,0.86,0.87,20.1939,20.6999,41.4,42.3,0.52,...,NaN,NaN,2.53663,2.49834,NaN,NaN,NaN,NaN,NaN,NaN
2742,2006-02-21 00:00:00,20.91,21.13,0.86,0.87,20.2399,20.3779,37.02,38.28,0.51,...,NaN,NaN,2.70893,2.53663,NaN,NaN,NaN,NaN,NaN,NaN
2744,2006-02-17 00:00:00,20.5,20.8,0.85,0.86,20.0099,20.3779,34.96,36.96,0.54,...,NaN,NaN,2.63235,2.80465,NaN,NaN,NaN,NaN,NaN,NaN
2746,2006-02-15 00:00:00,20.9,20.59,0.86,0.85,20.2399,20.5619,34.6,35.88,0.51,...,NaN,NaN,2.48877,2.48877,NaN,NaN,NaN,NaN,NaN,NaN
2748,2006-02-13 00:00:00,21.02,20.88,0.85,0.86,19.5039,20.2399,35.86,35.1,0.52,...,NaN,NaN,2.5462,2.39305,NaN,NaN,NaN,NaN,NaN,NaN
2750,2006-02-09 00:00:00,20.06,21.17,0.87,0.86,19.9639,19.9639,35.7,35.2,0.56,...,NaN,NaN,2.12503,2.34519,NaN,NaN,NaN,NaN,NaN,NaN
2752,2006-02-07 00:00:00,19.55,20.5,0.87,0.87,19.9179,19.5499,33.9,35.06,0.55,...,NaN,NaN,2.1346,2.1346,NaN,NaN,NaN,NaN,NaN,NaN
2754,2006-02-03 00:00:00,20.5,20.47,0.88,0.89,19.9179,19.9179,35.2,33.8,0.51,...,NaN,NaN,2.12503,2.12503,NaN,NaN,NaN,NaN,NaN,NaN
2756,2006-02-01 00:00:00,20.44,20.48,0.89,0.87,19.6419,20.0099,33.6,34.9,0.52,...,NaN,NaN,2.15374,2.15374,NaN,NaN,NaN,NaN,NaN,NaN
2758,2006-01-30 00:00:00,20.44,20.69,0.83,0.9,19.7799,19.9639,32.8,33.54,0.57,...,NaN,NaN,2.06759,2.2016,NaN,NaN,NaN,NaN,NaN,NaN
2760,2006-01-26 00:00:00,20,20,0.81,0.88,19.5499,19.5499,32.3,32,0.56,...,NaN,NaN,2.2016,2.2016,NaN,NaN,NaN,NaN,NaN,NaN
2762,2006-01-24 00:00:00,19.3,19.36,0.83,0.82,19.5499,19.7799,32.84,32.72,0.56,...,NaN,NaN,2.23032,2.15374,NaN,NaN,NaN,NaN,NaN,NaN
2764,2006-01-20 00:00:00,19.15,19.27,0.82,0.83,19.9179,19.7799,32.3,33.4,0.56,...,NaN,NaN,2.33561,2.24946,NaN,NaN,NaN,NaN,NaN,NaN
2766,2006-01-18 00:00:00,19.26,19.24,0.85,0.83,20.0099,19.7799,31.2,32.92,0.57,...,NaN,NaN,2.40262,2.41219,NaN,NaN,NaN,NaN,NaN,NaN
2768,2006-01-16 00:00:00,19.78,19.6,0.87,0.86,20.3779,20.6999,32.9,33,0.62,...,NaN,NaN,2.46005,2.40262,NaN,NaN,NaN,NaN,NaN,NaN
2770,2006-01-12 00:00:00,19,19.5,0.86,0.87,19.7339,19.8719,30.9,31.5,0.59,...,NaN,NaN,2.45048,2.46005,NaN,NaN,NaN,NaN,NaN,NaN
2772,2006-01-10 00:00:00,18.8,18.74,0.87,0.88,19.7339,19.7799,31.8,31.5,0.68,...,NaN,NaN,2.44091,2.44091,NaN,NaN,NaN,NaN,NaN,NaN
2774,2006-01-06 00:00:00,17.87,18.05,0.85,0.9,19.9179,20.0099,28.26,29.64,0.32,...,NaN,NaN,2.46963,2.46005,NaN,NaN,NaN,NaN,NaN,NaN
2776,2006-01-04 00:00:00,17.34,17.65,0.84,0.86,19.7799,19.5499,28.6,28.72,0.3,...,NaN,NaN,2.22075,2.69936,NaN,NaN,NaN,NaN,NaN,NaN
2778,2006-01-02 00:00:00,17.01,17.44,0.83,0.86,20.2399,19.6419,26.84,28.46,0.26,...,NaN,NaN,2.48877,2.53663,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
xl.sheet_names
df.head()
print(xl.sheet_names)

['Control', 'TS', 'CDAX', 'General', 'FY0', 'FY-1', 'FY-2', 'FY-3', 'FY-4', 'FY-5', 'FY-6']

In [72]:
n = (len(dfTime)-1)/2
n

1389.0

In [ ]:
for num in range(1,20):

In [69]:


numcols = len(dfTime.ix[:, 2::2])
numcols

2779

In [5]:
print(df.head())

        ID          ISIN  Normalized EBITDA  Normalized EBIT  \
0  TGTG.DE  DE0005118806          2314000.0       -6112000.0
1  UUUG.DE  DE0005167902          4037000.0         909000.0
2  VSCk.DE  DE000A14KL72         -7966000.0       -8969000.0
3  HRPKk.F  DE000A11QW68         21662000.0        9910000.0
4   LUMG.F  DE0006492903           245560.0         243940.0

   Normalized Income Before Taxes  Normalized Income After Taxes  \
0                      -5926000.0                     -6274100.0
1                       -286000.0                      -735000.0
2                      -9242000.0                     -9263100.0
3                       4692000.0                      4072430.0
4                        238940.0                       238940.0

   Total Revenue   Total Debt  Accounts Receivable - Trade, Net  \
0     53535000.0          0.0                        11092000.0
1     50575000.0   28178000.0                         6912000.0
2      3266000.0          0.0                          102000.0
3     25362000.0  181504000.0                         1353000.0
4     12433970.0         80.0                          183850.0

   Accounts Payable         ...           Net Debt - Mean  Total Debt.1  \
0         1071000.0         ...                -2500000.0           0.0
1         3517000.0         ...                       NaN    28178000.0
2          688000.0         ...               -14321330.0           0.0
3         1679000.0         ...               139890000.0   181504000.0
4          201890.0         ...                       NaN          80.0

   Total Current Assets  Total Current Liabilities  Total Liabilities  \
0            32189000.0                  9794000.0         11440000.0
1            23335000.0                 11917000.0         37010000.0
2            22415000.0                  5593000.0          7064000.0
3            31366000.0                 20604000.0        202557000.0
4              685150.0                   555900.0          1366310.0

   Total Equity  Common Stock, Total  Shares Out - Common Stock Primary Issue  \
0    38204000.0           19111000.0                               19111090.0
1    39806000.0           35314000.0                               33130380.0
2    26428000.0           18967000.0                               18966650.0
3    62189000.0           40478000.0                               42358590.0
4      250630.0           10226000.0                                8000000.0

   Cash and Equivalents  Number of Employees
0                4000.0                698.0
1                   NaN                145.0
2            21475000.0                 44.0
3            13073000.0                 17.0
4                   NaN                  0.0

[5 rows x 23 columns]

In [8]:
np.std([1,3,4,6], ddof=1)

2.0816659994661326

In [49]:
np.std(df['Normalized Income After Taxes'], ddof=1)

1454934451.541977